version: "3.9"

services:

  tg_sale_of_course:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_sale_of_course
    environment:

      HOST_POSTGRES: postgres_sale_of_cours
      PORT_POSTGRES: 5432
      USER_POSTGRES: ${USER_POSTGRES}
      PASSWORD_POSTGRES: ${PASSWORD_POSTGRES}
      DATABASE_POSTGRES: ${DATABASE_POSTGRES}

      HOST_REDIS: redis
      PASSWORD_REDIS: ${PASSWORD_REDIS}
      REDIS_DATABASES: ${REDIS_DATABASES}

      TG_API: ${TG_API}
      PROVIDER_TOKEN: ${PROVIDER_TOKEN}

    volumes:
      - ./logs:/logs

    depends_on:
      - db
      - redis

    networks:
      - sale_of_cours_bot_postgres_network

volumes:
  logs:
    driver: local

networks:
  sale_of_cours_bot_postgres_network:
